fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.15.0'
    concat:
      repo: 'puppetlabs/concat'
      ref: '2.2.1'
    postfix:
      repo: 'thias/postfix'
      ref: '0.3.4'
    augeasproviders_shellvar:
      repo: 'herculesteam/augeasproviders_shellvar'
      ref: '3.0.0'
    augeasproviders_core:
      repo: 'herculesteam/augeasproviders_core'
      ref: '2.1.4'
    augeasproviders_ssh:
      repo: 'herculesteam/augeasproviders_ssh'
      ref: '3.1.0'
    apt:
      repo: 'puppetlabs/apt'
      ref: '2.3.0'
    staging:
      repo: 'puppet/staging'
      ref: '2.2.0'
  repositories:
    rabbitmq:
      repo: 'git://github.com/willaerk/puppetlabs-rabbitmq.git'
      ref: 'cdcb352'
  symlinks:
    profiles: "#{source_dir}"
