fixtures:
  forge_modules:
    augeas_core:
      repo: 'puppetlabs/augeas_core'
      ref: '1.3.0'
    cron_core:
      repo: 'puppetlabs/cron_core'
      ref: '1.2.0'
    mount_core:
      repo: 'puppetlabs/mount_core'
      ref: '1.2.0'
    sshkeys_core:
      repo: 'puppetlabs/sshkeys_core'
      ref: '2.4.0'
    augeasproviders_core:
      repo: 'puppet/augeasproviders_core'
      ref: '3.2.0'
    augeasproviders_shellvar:
      repo: 'puppet/augeasproviders_shellvar'
      ref: '5.0.0'
    augeasproviders_sysctl:
      repo: 'herculesteam/augeasproviders_sysctl'
      ref: '2.6.2'
    augeasproviders_ssh:
      repo: 'puppet/augeasproviders_ssh'
      ref: '5.0.0'
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.25.0'
    concat:
      repo: 'puppetlabs/concat'
      ref: '4.2.1'
    postfix:
      repo: 'thias/postfix'
      ref: '0.3.4'
    apt:
      repo: 'puppetlabs/apt'
      ref: '4.5.1'
    staging:
      repo: 'puppet/staging'
      ref: '2.2.0'
    lvm:
      repo: 'puppetlabs/lvm'
      ref: '1.0.1'
    ntp:
      repo: 'puppetlabs/ntp'
      ref: '7.0.0'
    apache:
      repo: 'puppetlabs/apache'
      ref: '6.3.0'
    mysql:
      repo: 'puppetlabs/mysql'
      ref: '6.2.0'
    nodejs:
      repo: 'puppet/nodejs'
      ref: '2.1.0'
    elasticsearch:
      repo: 'elastic/elasticsearch'
      ref: '6.2.1'
    datacat:
      repo: 'richardc/datacat'
      ref: '0.6.2'
    firewall:
      repo: 'puppetlabs/firewall'
      ref: '3.6.0'
    inifile:
      repo: 'puppetlabs/inifile'
      ref: '1.6.0'
    sudo:
      repo: 'saz/sudo'
      ref: '6.0.0'
    systemd:
      repo: 'puppet/systemd'
      ref: '4.2.0'
    redis:
      repo: 'puppet/redis'
      ref: '8.8.0'
    alternatives:
      repo: 'puppet/alternatives'
      ref: '3.0.0'
    gnupg:
      repo: 'golja/gnupg'
      ref: '1.2.3'
    java_ks:
      repo: 'puppetlabs/java_ks'
      ref: '2.2.0'
    docker:
      repo: 'puppetlabs/docker'
      ref: '4.1.2'
    timezone:
      repo: 'bashtoni/timezone'
      ref: '1.0.0'
    collectd:
      repo: 'puppet/collectd'
      ref: '7.0.0'
    postgresql:
      repo: 'puppetlabs/postgresql'
      ref: '8.2.1'
    puppetdb:
      repo: 'puppetlabs/puppetdb'
      ref: '7.13.0'
    hocon:
      repo: 'puppetlabs/hocon'
      ref: '1.1.0'
    puppet_authorization:
      repo: 'puppetlabs/puppet_authorization'
      ref: '0.5.1'
    puppet_certificate:
      repo: 'puppet/puppet_certificate'
      ref: '1.0.0'
    hiera:
      repo: 'puppet/hiera'
      ref: '5.0.1'
    fail2ban:
      repo: 'puppet/fail2ban'
      ref: '4.2.0'
    php:
      repo: 'puppet/php'
      ref: '8.2.0'
    logrotate:
      repo: 'puppet/logrotate'
      ref: '6.1.0'
  repositories:
    rabbitmq:
      repo: 'https://github.com/cultuurnet/puppetlabs-rabbitmq.git'
      ref: 'cdcb352'
    borgbackup:
      repo: 'https://github.com/cultuurnet/puppet-borgbackup.git'
      ref: '0c92c9b'
    glassfish:
      repo: 'https://github.com/cultuurnet/fatmcgav-glassfish.git'
      ref: 'be6c31f'
    mailcatcher:
      repo: 'https://github.com/cultuurnet/puppet-mailcatcher.git'
      ref: '9752479'
    resqueweb:
      repo: 'https://github.com/cultuurnet/puppet-resqueweb.git'
      ref: 'a64a185'
    aptly:
      repo: 'https://github.com/cultuurnet/puppet-aptly.git'
      ref: '74a1c76'
    icinga2:
      repo: 'https://github.com/cultuurnet/puppet-icinga2.git'
      ref: '6815f51'
  symlinks:
    profiles: "#{source_dir}"
