fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.13.0'
    concat:
      repo: 'puppetlabs/concat'
      ref: '2.2.1'
    postfix:
      repo: 'thias/postfix'
      ref: '0.3.4'
  symlinks:
    profiles: "#{source_dir}"
