fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.25.0'
    concat:
      repo: 'puppetlabs/concat'
      ref: '2.2.1'
    postfix:
      repo: 'thias/postfix'
      ref: '0.3.4'
    augeasproviders_shellvar:
      repo: 'herculesteam/augeasproviders_shellvar'
      ref: '4.0.0'
    augeasproviders_core:
      repo: 'herculesteam/augeasproviders_core'
      ref: '2.4.0'
    augeasproviders_ssh:
      repo: 'herculesteam/augeasproviders_ssh'
      ref: '3.1.0'
    apt:
      repo: 'puppetlabs/apt'
      ref: '2.3.0'
    staging:
      repo: 'puppet/staging'
      ref: '2.2.0'
    lvm:
      repo: 'puppetlabs/lvm'
      ref: '1.0.1'
    ntp:
      repo: 'puppetlabs/ntp'
      ref: '6.1.0'
    apache:
      repo: 'puppetlabs/apache'
      ref: '1.11.0'
    mysql:
      repo: 'puppetlabs/mysql'
      ref: '3.11.0'
    nodejs:
      repo: 'puppet/nodejs'
      ref: '2.1.0'
  repositories:
    rabbitmq:
      repo: 'https://github.com/willaerk/puppetlabs-rabbitmq.git'
      ref: 'cdcb352'
    borgbackup:
      repo: 'https://github.com/cultuurnet/puppet-borgbackup.git'
      ref: '0.5.0'
    glassfish:
      repo: 'https://github.com/willaerk/fatmcgav-glassfish.git'
      ref: 'be6c31f'
    php:
      repo: 'https://github.com/willaerk/puppet-php.git'
      ref: '15a1818'
    mailcatcher:
      repo: 'https://github.com/cultuurnet/puppet-mailcatcher.git'
      ref: '9752479'
    resqueweb:
      repo: 'https://github.com/cultuurnet/puppet-resqueweb.git'
      ref: '7353dd0'
  symlinks:
    profiles: "#{source_dir}"
