fixtures:
  forge_modules:
    augeas_core:
      repo: 'puppetlabs/augeas_core'
      ref: '1.0.5'
    cron_core:
      repo: 'puppetlabs/cron_core'
      ref: '1.0.3'
    mount_core:
      repo: 'puppetlabs/mount_core'
      ref: '1.0.4'
    sshkeys_core:
      repo: 'puppetlabs/sshkeys_core'
      ref: '1.0.3'
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.25.0'
    concat:
      repo: 'puppetlabs/concat'
      ref: '4.2.1'
    postfix:
      repo: 'thias/postfix'
      ref: '0.3.4'
    augeasproviders_shellvar:
      repo: 'herculesteam/augeasproviders_shellvar'
      ref: '4.0.0'
    augeasproviders_sysctl:
      repo: 'herculesteam/augeasproviders_sysctl'
      ref: '2.2.1'
    augeasproviders_core:
      repo: 'herculesteam/augeasproviders_core'
      ref: '2.4.0'
    augeasproviders_ssh:
      repo: 'herculesteam/augeasproviders_ssh'
      ref: '3.1.0'
    apt:
      repo: 'puppetlabs/apt'
      ref: '4.5.1'
    staging:
      repo: 'puppet/staging'
      ref: '2.2.0'
    lvm:
      repo: 'puppetlabs/lvm'
      ref: '1.0.1'
    ntp:
      repo: 'puppetlabs/ntp'
      ref: '6.1.0'
    apache:
      repo: 'puppetlabs/apache'
      ref: '6.3.0'
    mysql:
      repo: 'puppetlabs/mysql'
      ref: '6.2.0'
    nodejs:
      repo: 'puppet/nodejs'
      ref: '2.1.0'
    elasticsearch:
      repo: 'elastic/elasticsearch'
      ref: '6.2.1'
    datacat:
      repo: 'richardc/datacat'
      ref: '0.6.2'
    firewall:
      repo: 'puppetlabs/firewall'
      ref: '1.9.0'
    inifile:
      repo: 'puppetlabs/inifile'
      ref: '1.6.0'
    sudo:
      repo: 'saz/sudo'
      ref: '6.0.0'
    systemd:
      repo: 'camptocamp/systemd'
      ref: '2.10.0'
    alternatives:
      repo: 'puppet/alternatives'
      ref: '3.0.0'
    gnupg:
      repo: 'golja/gnupg'
      ref: '1.2.3'
    java_ks:
      repo: 'puppetlabs/java_ks'
      ref: '2.2.0'
    docker:
      repo: 'puppetlabs/docker'
      ref: '4.1.2'
  repositories:
    rabbitmq:
      repo: 'https://github.com/willaerk/puppetlabs-rabbitmq.git'
      ref: 'cdcb352'
    borgbackup:
      repo: 'https://github.com/cultuurnet/puppet-borgbackup.git'
      ref: '1ec925a'
    glassfish:
      repo: 'https://github.com/willaerk/fatmcgav-glassfish.git'
      ref: 'be6c31f'
    php:
      repo: 'https://github.com/willaerk/puppet-php.git'
      ref: 'f47aff9'
    mailcatcher:
      repo: 'https://github.com/cultuurnet/puppet-mailcatcher.git'
      ref: '9752479'
    resqueweb:
      repo: 'https://github.com/cultuurnet/puppet-resqueweb.git'
      ref: '4d60cc0'
    websockets:
      repo: 'https://github.com/cultuurnet/puppet-websockets.git'
      ref: '8bbec32'
    aptly:
      repo: 'https://github.com/cultuurnet/puppet-aptly.git'
      ref: '74a1c76'
    deployment:
      repo: 'https://github.com/cultuurnet/puppet-deployment.git'
      ref: 'd8672cf'
  symlinks:
    profiles: "#{source_dir}"
