#!/bin/bash

KEY_OWNERS=${1}
INPUT=$(/usr/bin/cat)

/usr/bin/echo ${INPUT} | /usr/bin/jq -r '.root_token' > ~/.vault_token

while IFS=',' read -ra OWNER; do
    for counter in `/usr/bin/seq 0 $(( ${#OWNER[@]} - 1 ))`; do
        owner="${OWNER[${counter}]}"
	key=$(/usr/bin/echo ${INPUT} | /usr/bin/jq -r ".unseal_keys_b64[${counter}]")

	if [ "${owner}" = 'Vault' ]; then
            /usr/bin/echo "${key}" > ~/encrypted_unseal_key
	fi

        /usr/bin/echo $(/usr/bin/jq -n --arg key "$owner" --arg value "$key" '{ ($key): ($value) }')
    done | /usr/bin/jq -s add
done <<< "${KEY_OWNERS}" | /usr/bin/jq '{ "vault_encrypted_unseal_keys": . }'
