mutate {
  rename       => { "[host][name]" => "host" }
  add_field    => { "[@metadata][log_type]" => "%{[fields][log_type]}" }
  add_field    => { "[@metadata][environment]" => "%{[fields][environment]}" }
  remove_field => ["beat", "tags", "source", "offset", "@version", "fields"]
}
