name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    if: ${{ ! github.event.pull_request.merged }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0

      - name: Install dependencies
        run: bundle install

      - name: Run syntax check
        run: bundle exec rake syntax

      - name: Run unit tests
        run: bundle exec rake spec
