name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0

      - name: Install dependencies
        run: bundle install

      - name: Run syntax check
        run: bundle exec rake syntax

      - name: Run unit tests
        run: bundle exec rake spec
